# Generated by Django 5.0.2 on 2024-03-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_posts_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(),
        ),
    ]
