# Generated by Django 5.0.2 on 2024-03-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_comments_date_alter_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='to_time',
            field=models.CharField(max_length=200),
        ),
    ]
